"""Predefined NPC templates with baseline stats and flags."""

from copy import deepcopy

MOB_TEMPLATES = {
    "warrior": {
        "level": 1,
        "combat_class": "Warrior",
        "hp": 30,
        "mp": 0,
        "sp": 10,
        "primary_stats": {"STR": 4, "CON": 3, "DEX": 3, "INT": 1, "WIS": 1, "LUCK": 1},
        "actflags": ["aggressive"],
        "skills": ["slash"],
        "equipment": ["IRON_SWORD", "IRON_HAUBERK", "LEATHER_BOOTS"],
    },
    "caster": {
        "level": 1,
        "combat_class": "Mage",
        "hp": 20,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 4, "LUCK": 1},
        "spells": ["magic missile"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "merchant": {
        "level": 1,
        "npc_type": "merchant",
        "roles": ["merchant"],
        "ai_type": "passive",
        "actflags": ["sentinel"],
        "equipment": ["WOOL_TUNIC", "WOOL_LEGGINGS"],
        "shop": {
            "buy_percent": 100,
            "sell_percent": 100,
            "hours": "0-24",
            "item_types": ["weapon", "armor"],
        },
        "merchant_markup": 1.0,
    },
    "mystic": {
        "level": 1,
        "combat_class": "Mystic",
        "hp": 28,
        "mp": 10,
        "sp": 12,
        "primary_stats": {"STR": 3, "CON": 3, "DEX": 4, "INT": 1, "WIS": 3, "LUCK": 1},
        "actflags": ["aggressive"],
        "skills": ["slash"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "LEATHER_BOOTS"],
    },
    "wizard": {
        "level": 1,
        "combat_class": "Wizard",
        "hp": 20,
        "mp": 35,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 5, "WIS": 3, "LUCK": 1},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "sorcerer": {
        "level": 1,
        "combat_class": "Sorcerer",
        "hp": 20,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 2, "LUCK": 2},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "mage": {
        "level": 1,
        "combat_class": "Mage",
        "hp": 20,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 4, "LUCK": 1},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "battlemage": {
        "level": 1,
        "combat_class": "Battlemage",
        "hp": 25,
        "mp": 20,
        "sp": 10,
        "primary_stats": {"STR": 3, "CON": 3, "DEX": 2, "INT": 3, "WIS": 2, "LUCK": 1},
        "spells": ["fireball"],
        "skills": ["slash"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_SWORD", "WOOL_TUNIC", "LEATHER_BOOTS"],
    },
    "necromancer": {
        "level": 1,
        "combat_class": "Necromancer",
        "hp": 20,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 4, "LUCK": 1},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "spellbinder": {
        "level": 1,
        "combat_class": "Spellbinder",
        "hp": 20,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 2, "LUCK": 3},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "priest": {
        "level": 1,
        "combat_class": "Priest",
        "hp": 24,
        "mp": 25,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 3, "DEX": 2, "INT": 2, "WIS": 4, "LUCK": 1},
        "spells": ["heal"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "paladin": {
        "level": 1,
        "combat_class": "Paladin",
        "hp": 30,
        "mp": 15,
        "sp": 10,
        "primary_stats": {"STR": 3, "CON": 3, "DEX": 2, "INT": 1, "WIS": 3, "LUCK": 1},
        "skills": ["slash"],
        "spells": ["heal"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_SWORD", "IRON_HAUBERK", "LEATHER_BOOTS"],
    },
    "druid": {
        "level": 1,
        "combat_class": "Druid",
        "hp": 24,
        "mp": 25,
        "sp": 5,
        "primary_stats": {"STR": 2, "CON": 3, "DEX": 2, "INT": 1, "WIS": 4, "LUCK": 1},
        "spells": ["heal"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "LEATHER_BOOTS"],
    },
    "shaman": {
        "level": 1,
        "combat_class": "Shaman",
        "hp": 22,
        "mp": 25,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 2, "WIS": 4, "LUCK": 2},
        "spells": ["fireball", "heal"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "rogue": {
        "level": 1,
        "combat_class": "Rogue",
        "hp": 24,
        "mp": 0,
        "sp": 15,
        "primary_stats": {"STR": 2, "CON": 2, "DEX": 4, "INT": 1, "WIS": 1, "LUCK": 3},
        "skills": ["slash"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_DAGGER", "LEATHER_BOOTS"],
    },
    "ranger": {
        "level": 1,
        "combat_class": "Ranger",
        "hp": 26,
        "mp": 10,
        "sp": 12,
        "primary_stats": {"STR": 2, "CON": 2, "DEX": 4, "INT": 1, "WIS": 3, "LUCK": 2},
        "skills": ["slash"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "LEATHER_BOOTS"],
    },
    "warlock": {
        "level": 1,
        "combat_class": "Warlock",
        "hp": 22,
        "mp": 30,
        "sp": 5,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 2, "INT": 4, "WIS": 2, "LUCK": 3},
        "spells": ["fireball"],
        "actflags": ["sentinel"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "WOOL_LEGGINGS"],
    },
    "bard": {
        "level": 1,
        "combat_class": "Bard",
        "hp": 24,
        "mp": 20,
        "sp": 10,
        "primary_stats": {"STR": 1, "CON": 2, "DEX": 3, "INT": 3, "WIS": 2, "LUCK": 3},
        "spells": ["heal"],
        "skills": ["slash"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_DAGGER", "WOOL_TUNIC", "LEATHER_BOOTS"],
    },
    "swashbuckler": {
        "level": 1,
        "combat_class": "Swashbuckler",
        "hp": 26,
        "mp": 0,
        "sp": 15,
        "primary_stats": {"STR": 2, "CON": 2, "DEX": 4, "INT": 1, "WIS": 1, "LUCK": 3},
        "skills": ["slash"],
        "actflags": ["aggressive"],
        "equipment": ["IRON_SWORD", "LEATHER_BOOTS"],
    },
}


def get_template(name: str):
    """Return a deep copy of the template dictionary."""
    data = MOB_TEMPLATES.get(name.lower())
    if data:
        return deepcopy(data)
    return None
